version: '3.8'

services:
  ergo-node:
    build:
      context: .
      args:
        VERSION: ${ERGO_VERSION:-5.0.14}
    container_name: shark-node
    restart: unless-stopped
    ports:
      - "${NODE_PORT:-9053}:9053"
      - "${API_PORT:-9052}:9052"
    volumes:
      - ergo-data:/opt/ergo/data
    environment:
      - JAVA_OPTS=-Xmx${JAVA_HEAP:-2g}
    networks:
      - ergo-network

volumes:
  ergo-data:

networks:
  ergo-network:
    driver: bridge