version: '3.8'

services:
  ergo-node:
    build:
      context: .
      args:
        VERSION: ${ERGO_VERSION:-5.0.14}
    container_name: shark-node
    restart: unless-stopped
    ports:
      - "${NODE_PORT:-9053}:9053"
      - "${API_PORT:-9052}:9052"
    volumes:
      - ergo-data:/opt/ergo/data
      - ergo-wallet:/opt/ergo/wallet
    environment:
      - JAVA_OPTS=-Xmx${JAVA_HEAP:-2g}
      - ENABLE_METRICS=true
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=9052"
      - "prometheus.io/path=/metrics"
    networks:
      - ergo-network

volumes:
  ergo-data:
  ergo-wallet:

networks:
  ergo-network:
    driver: bridge