global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ergo-node'
    static_configs:
      - targets: ['ergo-node:9052']
    metrics_path: '/metrics'
    scheme: http

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
